DROP TABLE IF EXISTS tb_m_freqs CASCADE;
CREATE TABLE tb_m_freqs(
	freq_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	freq_nm character varying(20) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
	unique(freq_nm),
    deleted_dt timestamp without time zone
);

DROP TABLE IF EXISTS tb_m_zones CASCADE;
CREATE TABLE tb_m_zones(
	zone_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	zone_nm character varying(20) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone,
	unique(zone_nm)
);

DROP TABLE IF EXISTS tb_m_kanbans CASCADE;
CREATE TABLE tb_m_kanbans(
	kanban_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	line_id integer not null,
	kanban_nm character varying(20) not null,
	area_nm character varying(200) not null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone,
	unique(kanban_nm),
	constraint fk_tb_m_kanbans_line foreign key (line_id) references tb_m_lines (line_id)
);

DROP TABLE IF EXISTS tb_m_schedules CASCADE;
CREATE TABLE tb_m_schedules(
	schedule_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	"uuid" uuid not null,
	"date" date not null,
	week_pos integer not null, 
	is_holiday boolean null,
	holiday_nm character varying(200) null, 
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone
);

DROP TABLE IF EXISTS tb_m_roles CASCADE;
DROP TABLE IF EXISTS tb_m_roles CASCADE;
CREATE TABLE tb_m_roles(
	role_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	role_nm character varying(150) not null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone
);

DROP TABLE IF EXISTS tb_m_4s_members CASCADE;
CREATE TABLE tb_m_4s_members(
	member_4s_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	role_id integer not null,
	user_id integer not null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone,
	constraint fk_tb_m_4s_members_user foreign key (user_id) references tb_m_users (user_id),
	constraint fk_tb_m_4s_members_role foreign key (role_id) references tb_m_roles (role_id)
);

-- tb_r_clean_plans
DROP TABLE IF EXISTS tb_r_4s_plans CASCADE;
CREATE TABLE tb_r_4s_plans(
	plan_4s_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	group_id integer not null,
	line_id integer not null,
	"month" character varying(20) not null,
	"year" integer not null,
	section_head_id integer null,
	line_head_id integer null,
	team_leader_id integer null,
	section_head_sign text null,
	line_head_sign text null,
	team_leader_sign text null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_plans_groups foreign key (group_id) references tb_m_groups (group_id),
	constraint fk_tb_r_4s_plans_lines foreign key (line_id) references tb_m_lines (line_id),
	constraint fk_fk_tb_r_4s_plans_sh foreign key (section_head_id) references tb_m_4s_members (member_4s_id),
	constraint fk_fk_tb_r_4s_plans_lh foreign key (line_head_id) references tb_m_4s_members (member_4s_id),
	constraint fk_fk_tb_r_4s_plans_tl foreign key (team_leader_id) references tb_m_4s_members (member_4s_id)
);

-- tb_r_clean_schedules
DROP TABLE IF EXISTS tb_r_4s_schedules CASCADE;
CREATE TABLE tb_r_4s_schedules(
	schedule_4s_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	plan_4s_id integer not null,
	pic_id integer not null,
	kanban_id integer not null,
	zone_id integer not null,
	freq_id integer not null,
	schedule_id integer not null,
	status character varying(50) null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_schedules_clean_plan foreign key (plan_4s_id) references tb_r_4s_plans (plan_4s_id),
	constraint fk_tb_r_4s_schedules_pic foreign key (pic_id) references tb_m_4s_members (member_4s_id),
	constraint fk_tb_r_4s_schedules_kanban foreign key (kanban_id) references tb_m_kanbans (kanban_id),
	constraint fk_tb_r_4s_schedules_zone foreign key (kanban_id) references tb_m_zones (zone_id),
	constraint fk_tb_r_4s_schedules_freq foreign key (freq_id) references tb_m_freqs (freq_id),
	constraint fk_tb_r_4s_schedules_date foreign key (schedule_id) references tb_m_schedules (schedule_id)
);

-- tb_r_clean_schedule_revisions
DROP TABLE IF EXISTS tb_r_4s_schedule_revisions CASCADE;
DROP TABLE IF EXISTS tb_r_4s_revisions CASCADE;
CREATE TABLE tb_r_4s_revisions(
	revision_4s_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	schedule_4s_id integer not null,
	freq_nm character varying(100) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone,
	constraint fk_tb_r_clean_schedule_revisions_schedule  foreign key (schedule_4s_id) references tb_r_4s_schedules (schedule_4s_id)
);

DROP TABLE IF EXISTS tb_r_4s_checkers CASCADE;
CREATE TABLE tb_r_4s_checkers(
	checker_4s_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	plan_4s_id integer not null,
	"date" date null,
	week_pos integer not null, 
	checker_nm character varying(100) null,
	is_tl boolean null,
	is_gl boolean null,
	is_sh boolean null,
	sign text null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
    changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by character varying(100) DEFAULT NULL::character varying,
    deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_checkers_plan foreign key (plan_4s_id) references tb_r_4s_plans (plan_4s_id)
);