DROP TABLE IF EXISTS tb_m_roles CASCADE;
DROP TABLE IF EXISTS tb_m_4s_members CASCADE;
DROP TABLE IF EXISTS tb_r_4s_plans CASCADE;
DROP TABLE IF EXISTS tb_r_4s_schedules CASCADE;
DROP TABLE IF EXISTS tb_r_4s_checkers CASCADE;
DROP TABLE IF EXISTS tb_r_4s_sign_checkers CASCADE;
DROP TABLE IF EXISTS tb_m_freqs CASCADE;
CREATE TABLE tb_m_freqs(
	freq_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	freq_nm character varying(20) NOT NULL,
	precition_val integer not null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	unique(freq_nm),
	deleted_dt timestamp without time zone
);
DROP TABLE IF EXISTS tb_m_zones CASCADE;
CREATE TABLE tb_m_zones(
	zone_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	freq_id integer not null,
	line_id integer not null,
	zone_nm character varying(20) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	unique(freq_id, zone_nm),
	constraint fk_tb_m_zones_line foreign key (line_id) references tb_m_lines (line_id),
	constraint fk_tb_m_zones_freq foreign key (freq_id) references tb_m_freqs (freq_id)
);
DROP TABLE IF EXISTS tb_m_kanbans CASCADE;
CREATE TABLE tb_m_kanbans(
	kanban_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	zone_id integer not null,
	area_nm character varying(200) not null,
	kanban_no character varying(20) not null,
	kanban_imgs text null,
	-- imgs...; imgs...;
	standart_time integer null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	unique(zone_id, kanban_no, area_nm),
	constraint fk_tb_m_kanbans foreign key (zone_id) references tb_m_zones (zone_id)
);
DROP TABLE IF EXISTS tb_m_item_check_kanbans CASCADE;
DROP TABLE IF EXISTS tb_m_4s_item_check_kanbans CASCADE;
CREATE TABLE tb_m_4s_item_check_kanbans(
	item_check_kanban_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid uuid not null,
	kanban_id integer not null,
	item_check_nm character varying(150) not null,
	standart_time numeric(5, 2) not null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	unique(kanban_id, item_check_nm),
	constraint fk_tb_m_4s_item_check_kanbans_kanban foreign key (kanban_id) references tb_m_kanbans (kanban_id)
);
DROP TABLE IF EXISTS tb_m_schedules CASCADE;
CREATE TABLE tb_m_schedules(
	schedule_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	"uuid" uuid not null,
	"date" date not null,
	-- week_num integer not null, 
	is_holiday boolean null,
	holiday_nm character varying(200) null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone
);
DROP TABLE IF EXISTS tb_m_4s_opt_changes CASCADE;
CREATE TABLE tb_m_4s_opt_changes(
	opt_change_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	opt_nm character varying(250) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	unique(opt_nm)
);
DROP TABLE IF EXISTS tb_m_4s_opt_depts CASCADE;
CREATE TABLE tb_m_4s_opt_depts(
	opt_dept_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	dept_nm character varying(250) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	unique(dept_nm)
);
DROP TABLE IF EXISTS tb_m_4s_evaluations CASCADE;
CREATE TABLE tb_m_4s_evaluations(
	evaluation_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	evaluation_nm character varying(250) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	unique(evaluation_nm)
);
-- tb_r_4s_plans
DROP TABLE IF EXISTS tb_r_4s_main_schedules CASCADE;
CREATE TABLE tb_r_4s_main_schedules(
	main_schedule_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	group_id integer not null,
	line_id integer not null,
	month_num integer not null,
	year_num integer not null,
	section_head_sign text null,
	group_leader_sign text null,
	team_leader_sign text null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_main_schedules_groups foreign key (group_id) references tb_m_groups (group_id),
	constraint fk_tb_r_4s_main_schedules_lines foreign key (line_id) references tb_m_lines (line_id)
);
-- tb_r_4s_schedules
DROP TABLE IF EXISTS tb_r_4s_sub_schedules CASCADE;
CREATE TABLE tb_r_4s_sub_schedules(
	sub_schedule_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	main_schedule_id integer not null,
	kanban_id integer not null,
	zone_id integer not null,
	freq_id integer not null,
	schedule_id integer not null,
	plan_pic_id integer null,
	actual_pic_id integer null,
	plan_time timestamp null,
	actual_time timestamp null,
	shift character varying(50) null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_sub_schedules_main foreign key (main_schedule_id) references tb_r_4s_main_schedules (main_schedule_id),
	constraint fk_tb_r_4s_sub_schedules_plan_pic foreign key (plan_pic_id) references tb_m_users (user_id),
	constraint fk_tb_r_4s_sub_schedules_actual_pic foreign key (actual_pic_id) references tb_m_users (user_id),
	constraint fk_tb_r_4s_sub_schedules_kanban foreign key (kanban_id) references tb_m_kanbans (kanban_id),
	constraint fk_tb_r_4s_sub_schedules_zone foreign key (zone_id) references tb_m_zones (zone_id),
	constraint fk_tb_r_4s_sub_schedules_freq foreign key (freq_id) references tb_m_freqs (freq_id),
	constraint fk_tb_r_4s_sub_schedules_date foreign key (schedule_id) references tb_m_schedules (schedule_id)
);
DROP TABLE IF EXISTS tb_r_4s_schedule_item_check_kanbans CASCADE;
CREATE TABLE tb_r_4s_schedule_item_check_kanbans(
	schedule_item_check_kanban_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	sub_schedule_id integer not null,
	item_check_kanban_id integer not null,
	actual_time integer not null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_schedule_item_check_kanbans_sub_schedule foreign key (sub_schedule_id) references tb_r_4s_sub_schedules (sub_schedule_id),
	constraint fk_tb_r_4s_schedule_item_check_kanbans_master foreign key (item_check_kanban_id) references tb_m_4s_item_check_kanbans (item_check_kanban_id)
);
-- tb_r_clean_schedule_revisions
DROP TABLE IF EXISTS tb_r_4s_schedule_revisions CASCADE;
CREATE TABLE tb_r_4s_schedule_revisions(
	schedule_revision_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	sub_schedule_id integer not null,
	freq_nm character varying(100) NOT NULL,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	constraint fk_tb_r_clean_schedule_revisions_schedule foreign key (sub_schedule_id) references tb_r_4s_sub_schedules (sub_schedule_id)
);
DROP TABLE IF EXISTS tb_r_4s_schedule_sign_checkers CASCADE;
CREATE TABLE tb_r_4s_schedule_sign_checkers(
	sign_checker_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	main_schedule_id integer not null,
	start_date date null,
	end_date date null,
	-- week_num integer not null, 
	is_tl_1 boolean null,
	is_tl_2 boolean null,
	is_gl boolean null,
	is_sh boolean null,
	sign text null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_schedule_sign_checkers_schedule foreign key (main_schedule_id) references tb_r_4s_main_schedules (main_schedule_id)
);
DROP TABLE IF EXISTS tb_r_4s_findings CASCADE;
CREATE TABLE tb_r_4s_findings(
	finding_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
	uuid UUID not null,
	freq_id integer not null,
	zone_id integer not null,
	kanban_id integer not null,
	pic_id integer not null,
	evaluation_id integer not null,
	finding_desc text not null,
	plan_cm_desc text not null,
	time_cm integer null,
	time_yokoten integer null,
	opt_change_ids text null,
	-- perubahan 1; perubahan 2; perubahan3
	opt_dept_ids text null,
	-- dept1; dept2; dpet3
	plan_cm_time timestamp null,
	actual_cm_time timestamp null,
	actual_pic_nm character varying(100) NOT NULL,
	finding_img text null,
	created_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	created_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_by character varying(100) DEFAULT 'SYSTEM'::character varying NOT NULL,
	changed_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_by character varying(100) DEFAULT NULL::character varying,
	deleted_dt timestamp without time zone,
	constraint fk_tb_r_4s_findings_kanban foreign key (kanban_id) references tb_m_kanbans (kanban_id),
	constraint fk_tb_r_4s_findings_zone foreign key (zone_id) references tb_m_zones (zone_id),
	constraint fk_tb_r_4s_findings_pic foreign key (pic_id) references tb_m_users (user_id),
	constraint fk_tb_r_4s_findings_evaluation foreign key (evaluation_id) references tb_m_4s_evaluations (evaluation_id),
	constraint fk_tb_r_4s_findings_freq foreign key (freq_id) references tb_m_freqs (freq_id)
);
DROP TABLE IF EXISTS tb_r_4s_pic_rotations CASCADE;