name: Deploy

on:
  push:
    branches:
      - master  # Trigger deployment on master branch changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy application
      run: |
        # Your deployment script goes here
        echo "Deploying your application"

    - name: Trigger API
      run: |
        # Assuming your deployment is successful and you want to trigger an API
        curl -X POST http://mt-system.id:9111/auto-deploy-win/4dm1nComp1teR