name: Deploy

on:
  push:
    branches:
      - master  # Trigger deployment on master branch changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Application
      run: |
        curl -X POST http://mt-system.id:9111/auto-deploy-win/4dm1nComp1teR